<?php
/** @var M2Boilerplate\WebAppManifest\Block\Adminhtml\Cache\Additional $block */
?>
<p>
    <button onclick="setLocation('<?php /* @escapeNotVerified */ echo $block->getCleanResizedImagesUrl() ?>')" type="button">
        <?php /* @escapeNotVerified */ echo __('Flush Resized Web App Manifest Icon Cache') ?>
    </button>
    <span><?php /* @escapeNotVerified */ echo __('Generated icons with M2Boilerplate Web App Manifest Module') ?></span>
</p>